const ActionTypes = {
    ADD_RECEIPT: 'ADD_RECEIPT',
    ADD_RECEIPT_SUCCESS: 'ADD_RECEIPT_SUCCESS',
    ADD_RECEIPT_FAIL: 'ADD_RECEIPT_FAIL',
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    GET_RECEIPT_SUCCESS: 'GET_RECEIPT_SUCCESS',
    GET_USER_SUCCESS: 'GET_USER_SUCCESS',
    GET_USER_RECEIPTS_SUCCESS: 'GET_USER_RECEIPTS_SUCCESS',
    LOGIN: "LOGIN",
}

export default ActionTypes;
